frontend-html/package.json
frontend-html/src/plugins/tools/PluginRegistration.ts
frontend-html/yarn.lock

dependency on @origam/plugin-radar-chart was removed

INTERNAL: Client now depend on @origam/plugin-chart

---

backend/Origam.ServerCommon/ExcelEntityExporter.cs

the actual limit was always bigger by 1

FIX: ExportRecordsLimit setting was not respected when the value was 1

---

.github/workflows/codeql-analysis-js.yml
.github/workflows/codeql-analysis.yml
.github/workflows/codeql-analysis_stable.yml
.github/workflows/yarn.yml

Extend actions with 2021.1 branche.  For test build backend for stable branche create new action.

INTERNAL: Extend actions with 2021.1 branche. 

---

backend/Origam.DA.Service-net2Tests/FilterCommandParserTests.cs
backend/Origam.DA.Service/CustomCommandParser/FilterNode.cs
frontend-html/src/gui/Components/ScreenElements/Table/FilterSettings/FilterSettings.tsx
frontend-html/src/gui/Components/ScreenElements/Table/FilterSettings/HeaderControls/FilterSettingsNumber.tsx

It would be great if this pull requst would not be squashed

Error on float in filter

---

.github/workflows/codeql-analysis.yml

Automatictestbuidarchitect

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBody.tsx

also, the dropdown width did not account for vertical scroll bar width and cell padding hiding part of the widest cell text

FIX: Dropdown height was not limited to 6 lines

---

frontend-html/src/gui/Workbench/ScreenArea/FormView/FormViewEditor.tsx

showing the original value after a change has been made

FIX: Field editors were not updated

---

backend/OrigamSetup/config/OrigamArchitect.exe.config

- architect installed via setup used old version of CompilerServices.Unsafe dll

Updated assembly binding

---

backend/OrigamSetup/config/OrigamArchitect.exe.config

- architect installed via setup used old version of CompilerServices.Unsafe dll

Updated assembly binding (#315)

---

build/build-monorepo_2022_1.yaml

Removed two duplicite steps.

---

backend/Origam.Server/Resources/SharedResources.cs-CZ.resx
backend/Origam.Server/Resources/SharedResources.de.resx
backend/Origam.Server/Resources/SharedResources.fr.resx
backend/Origam.Server/Resources/SharedResources.resx
backend/Origam.Server/Views/Account/ResetPassword.cshtml

Reset password UI

---

backend/Origam.Workflow.FileService/ExcelServiceAgent.cs

- added support for reading XLSX from blob

ExcelServiceAgent

---

backend/Origam.ServerCore/Configuration/IdentityServerConfig.cs
backend/Origam.ServerCore/Startup.cs
backend/Origam.ServerCore/TemplateFiles/_appsettings.json
frontend-html/yarn.lock

defaults: "CookieExpirationMinutes": 60, "CookieSlidingExpiration": true

NEW: Cookie lifetime can be set in the appsettings.json

---

backend/Origam.Server/IdentityServerGui/Account/AccountController.cs
backend/Origam.Server/TemplateFiles/testResetPwFile.txt
backend/Origam.Server/Views/Account/ResetPassword.cshtml

the email has to be included query string parameters. See "testResetPwFile.txt"

CHG: User email input was removed from the password reset page

---

frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/cells/dataCellRenderer.ts

FIX: GridColumnWidth was ignored

---

docker/startServer.sh

Improve startServer.sh.
Choose branch under ssh connection.
Check if model get from git correctly.

Dockerstartserver

---

backend/Origam.ServerCore/IApplicationBuilderExtensions.cs
backend/Origam.ServerCore/Middleware/UserApiMiddleWare.cs
backend/Origam.ServerCore/Middleware/UserApiMiddleware.cs

the default locale was always used

FIX: Modeled apis ignored localization cookie

---

docker/Dockerfile

Added  frontend source into HTML5-SOURCE directory. Added yarn for build frontend.

Added support for build frontend 

---

backend/Origam.ServerCore/IdentityServerGui/Account/AccountController.cs

If user has not email confirmed, during reset password process will be always email confirmed.

FIX: improve reset password logging.

---

model-root/model/Root/DataConstant/OrigamDataAuditLog_ActionType_Delete.origam
model-root/model/Root/DataEntity/__system/OrigamDataAuditLog.origam

* Adjusted filter for SQL to hit the index.

Audit log performance adjustments - 2021.1

---

model-root/model/Root/DataConstant/OrigamDataAuditLog_ActionType_Delete.origam
model-root/model/Root/DataEntity/__system/OrigamDataAuditLog.origam

* CHG: Adjusted filter for SQL to hit the index.

Audit log performance adjustments - 2022.1

---

model-root/model/Root/DataConstant/OrigamDataAuditLog_ActionType_Delete.origam
model-root/model/Root/DataEntity/__system/OrigamDataAuditLog.origam

* CHG: Adjusted filter for SQL to hit the index.

Audit log performance adjustments

---

backend/Origam.Mail/Origam.Mail.csproj

Upgrade framework of Origam.Mail

Upgrade framework.

---

backend/Origam.Server/Origam.Server.csproj
backend/Origam.sln
backend/Origam.workflow.mail/Origam.workflow.mail.csproj
backend/Origam.workflow.mail/WorkQueueImapLoaderAdapter.cs
backend/Origam.workflow.mail/WorkQueuePop3LoaderAdapter.cs

Added the project to Origam.Server.

Converted Origam.WorkFlow.Mail to netstandard 2.0.

---

frontend-html/src/gui/Components/Form/FieldDimensions.tsx

leading to the element being positioned at [0, 0]

FIX: Some form element coordinates were ignored

---

backend/Origam.Server/Configuration/IdentityServerConfig.cs
backend/Origam.Server/Startup.cs
backend/Origam.Server/TemplateFiles/_appsettings.json

- external login configurations moved to subsections, subsection presence means that login should be used

CHG: appsettings.json

---

backend/Origam.Server/IdentityServerGui/Account/ExternalController.cs

AuthenticationPostProcessor was invoked without checking whether the user was found in the system.

FIX: ExternalController

---

backend/Origam.Schema.WorkflowModel/SchemaItems/WorkQueue/WorkQueueClass.cs

Mandatory field rule on WorkQueueStructureSortSet

CHG: Model - WorkQueueClass

---

backend/Origam.Schema.EntityModel/EntityHelper.cs
backend/Origam.Schema.WorkflowModel/WorkflowHelper.cs

- sort set Default (RecordCreated ascending) is generated and assigned

CHG: Create Work Queue Class action

---

.github/workflows/codeql-analysis.yml
checkvstest.ps1

Revert "NUnit Tests failures weren't reported back to validation workflow"

---

frontend-html/src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx

If several tables had a common source entity the order number was decreased in all tables

FIX: Ordering was broken when deleting an item

---

model-root/model/Security/.origamPackage
model-root/model/Security/DataEntity/Security/OrigamIdentityGrant.origam
model-root/model/Security/DeploymentVersion/Security/5.4.1.origam
model-root/model/Security/DeploymentVersion/Security/5.4.1.origam___commandText___0a71752e-334f-4d3e-b818-84ec18607f00.txt
model-root/model/Security/DeploymentVersion/Security/5.4.1.origam___commandText___1e31ca2c-2d18-4507-bc71-edcd04f71efb.txt
model-root/model/Security/DeploymentVersion/Security/5.4.1.origam___commandText___324368b6-7768-4af1-a9e0-6b3b8ed42234.txt
model-root/model/Security/DeploymentVersion/Security/5.4.1.origam___commandText___651414c9-af75-473a-82be-4cf3e009fa4e.txt

Removed Bad Index on "Key" column on table OrigamIdentityGrant. Create a new create table sql scripts for Mssql and Postgresql databases.

Fixed a difference between model and database for table OrigamIdentityGrant.

---

frontend-html/src/gui/connections/MobileComponents/Form/ActionList.tsx
frontend-html/src/gui/connections/MobileComponents/Form/MobileAction.tsx

user had to close the list after finishing the action

FIX: Mobile action list was not closing after action click

---

.github/CODEOWNERS

to improve pull request approval process for e2e test

INTERNAL: Added test app owner

---

frontend-html/package.json
frontend-html/src/gui/connections/MobileComponents/Navigation/DetailNavigator.tsx
frontend-html/src/gui/connections/MobileComponents/Navigation/NavigationNode.tsx
frontend-html/yarn.lock

after coming back from a dialog

FIX: Mobile actions were disappearing

---

backend/Origam.Workbench/Commands/SchemaCommands.cs

Revert "WF PropertyGridEditor open after click on Action Edit Item."

---

backend/Origam.DA.Service/Generators/AbstractSqlCommandGenerator.cs
backend/Origam.DA.Service/Generators/MsSqlRenderer.cs
backend/Origam.DA.Service/Generators/PgSqlRenderer.cs
backend/Origam.DA.Service/Generators/SqlRenderer.cs

…eturns the character with the given code.

PGSQL rendering of CHAR function

---

frontend-html/src/gui/Workbench/ScreenArea/FormScreenBuilder/mobileRecursiveBuilder.ts

if there were no items to shown

FIX: Work queue screen could not be open in the mobile layout

---

build/build-monorepo.yaml

- into build_desktop_applications and build_server

BUILD: Job build_source split

---

backend/Origam.Gui.Win/Commands/MakeActiveVersionCurrent.cs
backend/Origam.Workbench/Pads/ExtensionPad.cs

after executing a deployment script

FIX: Package version was not updated in the Packages pad

---

frontend-html/custom-scripts/updateVersions.cjs

Plugin version can now be extracted from packages when tey are copied to the plugin/implementations directory.

INTERNAL: Plugin version detection made more robust

---

backend/Origam.Server/Configuration/IdentityServerConfig.cs
backend/Origam.Server/Settings.cs

and is compatible with official openid Android demo application

INTERNAL: origamMobileClient now uses Code grant type

---

backend/Origam.Server/assets/identity/css/main.css
backend/Origam.Server/assets/identity/js/browser-check.js

FIX: Some text on identity pages was aligned to the left

---

backend/Origam.DA.Service/PgSqlDataService.cs
backend/Origam.Server/Program.cs
backend/OrigamArchitect/MainClass.cs

stored procedure, and a function.

Npgsql 7.0 continue generates SQL for invoking a PostgreSQL 

---

backend/Origam.Server/Configuration/UserConfig.cs
backend/Origam.Server/Startup.cs

* Enable configuration of username allowed characters
* Refactoring
---------

NEW: Enable configuration of username allowed characters

---

backend/Origam.Workflow/WorkQueue/WorkQueueService.cs

- transaction id wasn't passed to evaluator causing database connection timeout

FIX: Work Queue Command Condition

---

backend/Origam.Gui/OrigamPanelFilterDA.cs

if type of the filtered column was string but actually contained guids

FIX: Guid filter value was not saved

---

backend/Origam.Workflow/Engine.cs
backend/Origam.Workflow/WorkFlowStackTrace_.cs
backend/Origam.Workflow/WorkflowStackTrace.cs

Fixed casing in the class name and filename.

DEV: WorkflowStackTrace refactoring

---

frontend-html/package.json
frontend-html/yarn.lock

was interpreted as day of year

FIX: Day of week was not translated correctly to moment format

---

frontend-html/package.json
frontend-html/yarn.lock

was interpreted as day of year

FIX: Day of week in format 2022 4

---

model-tests/model/Security/DataStructure/Security/OrigamIdentityGrant.origam

user is forced to logout after approx. 15 minutes in demo project

DEV: Security package updated in demo project

---

backend/Origam.DA.Service/Generators/PgSqlCommandGenerator.cs

PostgreSQL input procedure parameters didn't have ParameterDeclarationChar.

FIX: PostgreSQL input procedure parameters were without ParameterDeclarationChar.

---

frontend-html/src/model/entities/RowState.ts

leading to very long load times when scrolling over big number of rows

FIX: Too many row states were requested

---

backend/Origam.Common/ConfigurationManager.cs
backend/Origam.Workbench/OrigamSettingsEditor.cs

when OrigamSettingsEditor is open

FEATURE: Status bar shows OrigamSettings location

---

model-tests/model/AutomaticTests/.origamPackage
model-tests/model/AutomaticTests/DeploymentVersion/AutomaticTests/1.0.1.origam
model-tests/model/AutomaticTests/DeploymentVersion/AutomaticTests/1.0.1.origam___commandText___7075d987-d6b8-4dd7-b3e3-3f14ff3f5434.txt
model-tests/model/Widgets/Control/TagInputSource.origam
model-tests/model/Widgets/DataStructure/Widgets/TagInputSource.origam
model-tests/model/Widgets/FormControlSet/Widgets/TagInputSource.origam
model-tests/model/Widgets/Menu/Menu.origam
model-tests/model/Widgets/PanelControlSet/Widgets/TagInputSource.origam

Added screen for master data - taginput source and then created a stored procedure that creates data for replicating a bug with lookup horizontal scrollbar.
---------

DEV: Test model adjustments

---

frontend-html/src/model/entities/RowState.ts

leading to very long load times when scrolling over big number of rows

FIX: Too many row states were requested 2022.4

---

frontend-html/src/model/actions-ui-tree/actions.ts
frontend-html/src/model/entities/OrigamAPI.ts
frontend-html/src/model/entities/types/IApi.ts
frontend-html/src/model/entities/types/IDataView.ts

* Allow intercepting actions before potential error is handled in a dialog. 
* Provide blob url (e.g. to be used as iframe src).
* Improve types to make focusFormViewControl accessible in IDataView interface.

FEATURE: Improve plugin infrastructure

---

backend/OrigamArchitect/NewProjectWizard.Designer.cs
backend/OrigamArchitect/NewProjectWizard.cs

because it was not compatible with the deployment options (Docker)

FIX: Integrated authentication removed from New Project Wizard

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

Last valid dropdown value was selected after pressing enter even though the current text in the input resulted in no valid values in the dropdown

FIX: Invalid option used in lookup with emptied dropdown

---

backend/Origam.Gui.Win/AsTextBox.cs
backend/Origam.OrigamEngine/ModelXmlBuilders/FormXmlBuilder.cs
backend/Origam.OrigamEngine/ModelXmlBuilders/TextBoxBuilder.cs
frontend-html/src/gui/Components/ScreenElements/Editors/TextEditor.tsx
frontend-html/src/gui/Workbench/ScreenArea/FormView/FormViewEditor.tsx
frontend-html/src/gui/Workbench/ScreenArea/TableView/TableViewEditor.tsx
frontend-html/src/model/entities/Property.ts
frontend-html/src/model/entities/types/IProperty.ts
frontend-html/src/xmlInterpreters/screenXml.ts
model-root/model/Root/Control/_Basic Controls/AsTextBox.origam
model-tests/model/Root/Control/_Basic Controls/AsTextBox.origam
model-tests/model/Widgets/Control/AllDataTypes.origam
model-tests/model/Widgets/PanelControlSet/Widgets/AllDataTypes.origam

<kbd>Tab</kbd> key inserts Tab character when this behaviour is enabled in the model.

FEATURE: Allow tab character in textboxes (master)

---

frontend-html/src/gui/connections/CScreenHeader.tsx
frontend-html/src/model/entities/DataView.ts
frontend-html/src/model/entities/RowState.ts

Revert "FIX: Busy indicator was not active right after row states were requested 2022.4"

---

frontend-html/src/model/entities/RowState.ts

FIX: Work queue actions disappearing 2022 4

---

frontend-html/src/model/entities/RowState.ts

Work queue delete action was disappearing after clicking on select all rows because of missing row states

FIX: Work queue delete action disappearing

---

backend/Origam.Server/Common/PortalResult.cs
backend/Origam.Server/Configuration/HtmlClientConfig.cs
backend/Origam.Server/Controller/UIServiceController.cs
backend/Origam.Server/TemplateFiles/_appsettings.json
frontend-html/src/model/entities/RowState.ts
frontend-html/src/model/entities/WorkbenchLifecycle/WorkbenchLifecycle.ts
frontend-html/src/model/entities/types/IPortalSettings.ts
frontend-html/src/xmlInterpreters/screenXml.ts

* Fixed camel casing for milliseconds.

DEV: Refactoring milliseconds (#1803)

---

.github/workflows/nunit-tests.yml

latest version of dotnet broke the tests

BUILD: nunit tests are run with 6.0 sdk

---

frontend-html/src/gui/connections/NotificationContainer.tsx

when notifications were not sent from the server

FIX: Report fails 2022 4

---

frontend-html/src/gui/connections/NotificationContainer.tsx

when notifications were not sent from the server

 FIX: Report fails 

---

frontend-html/src/gui/connections/NotificationContainer.tsx

when notifications were not sent from the server

FIX: Report fails 2023 1

---

backend/Origam.Server/IApplicationBuilderExtensions.cs
backend/Origam.Server/Middleware/OptionalTokenAuthenticationMiddleware.cs
backend/Origam.Server/Middleware/UserApiTokenAuthenticationMiddleware.cs

authorization should be optional

FIX: Authentication in work queue api made optional 2023.1

---

backend/Origam.Workbench.Services/ParameterService.cs
backend/Origam.Workbench.Services/Strings.resx

If there are multiple constants of the same name in the model.

FEATURE: Architect displays conflicting constant name

---

backend/Origam.Workbench.Services/ParameterService.cs
backend/Origam.Workbench.Services/Strings.resx

If there are multiple constants of the same name in the model.

FEATURE: Architect displays conflicting constant name 2023.1

---

model-root/model/Root/DeploymentVersion/_origam_root/5.3.origam___commandText___f92c7cc1-f0c9-41da-a148-3bd3f769b8ad.txt
model-tests/model/Root/DeploymentVersion/_origam_root/5.3.origam___commandText___f92c7cc1-f0c9-41da-a148-3bd3f769b8ad.txt

The deployment scripts required following languages to be present in table Language: de-DE, de-CH, cs-CZ.

FIX: Localization deployment script failure

---

frontend-html/src/model/entities/DataSource.ts
frontend-html/src/model/entities/FormScreen.ts
frontend-html/src/model/entities/RowState.ts
frontend-html/src/model/entities/WorkbenchLifecycle/WorkbenchLifecycle.ts
frontend-html/src/model/entities/types/IDataSource.ts
frontend-html/src/model/entities/types/IFormScreen.ts
frontend-html/src/model/entities/types/IRowState.ts

exception occured in rowSates endpoint

FIX: Session expired exception was throw after reopening a screen

---

frontend-html/src/model/entities/DataSource.ts
frontend-html/src/model/entities/FormScreen.ts
frontend-html/src/model/entities/RowState.ts
frontend-html/src/model/entities/WorkbenchLifecycle/WorkbenchLifecycle.ts
frontend-html/src/model/entities/types/IDataSource.ts
frontend-html/src/model/entities/types/IFormScreen.ts
frontend-html/src/model/entities/types/IRowState.ts

exception occured in rowSates endpoint

FIX: Session expired exception was throw after reopening a screen 2023.1

---

frontend-html/src/gui/connections/CScreen.tsx
frontend-html/src/model/entities/OrigamAPI.ts
frontend-html/src/model/entities/types/IApi.ts

because it broke most of the web reports.

FIX: Indirect iframe content loading was reverted

---

frontend-html/src/gui/connections/CScreen.tsx
frontend-html/src/model/entities/OrigamAPI.ts
frontend-html/src/model/entities/types/IApi.ts

because it broke most of the web reports.

FIX: Indirect iframe content loading was reverted 2023.1

---

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts
frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx

FIX: Grid was not focused after pressing F2 or Esc 2023.1

---

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts
frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx

FIX: Grid was not focused after pressing F2 or Esc

---

backend/Origam.Gui/UIActionTools.cs

FEATURE: Panel header action buttons not shown if set to be ignored

---

frontend-html/src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx

FIX: Some details were not copied when copying the master

---

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts

FIX: Focus on Ctl +S lost in grid editor

---

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts

FIX: Focus on Ctl +S lost in grid editor 2023.1

---

backend/Origam.Schema.MenuModel/SchemaItems/FormReferenceMenuItem.cs

if ListDataStructure was defined

FIX: Missing ListEntity caused an ObjectReferenceException

---

build/build-monorepo_2023_1.yaml

Added support for create windows base docker image. Need to be approved pull request  with a docker directory change.

FEATURE: Windows docker image for 2023.1

---

backend/Origam.Workflow/WorkQueue/WorkQueueWorkflowLoader.cs

Revert "FIX: Work queue loader now returns 0 items when only empty <ROOT/> el…"

---

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts
frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx

when the horizontal scroll bar was not all the way to the left

FIX: Focus lost when scrolled right and pressing enter in an editor 2023 1

---

backend/Origam.Server/Controller/AbstractController.cs
frontend-html/src/model/actions-ui/RecordInfo/onRecordInfoClick.ts
frontend-html/src/model/actions-ui/onSelectedRowChange.ts
frontend-html/src/model/entities/RecordInfo.ts
frontend-html/src/model/entities/types/IApi.ts
frontend-html/src/model/entities/types/IRecordInfo.ts

i.e. row has just been created but not saved yet

FIX: Record info was not displayed for new rows 2023.1

---

backend/Origam.Server/Session Stores/WorkflowSessionStore.cs

a new notification was added instead

FIX: Overriding a workflow notification did not work

---

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateTimeEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/NumberEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/TagInputEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/TextEditor.tsx
frontend-html/src/gui/Workbench/ScreenArea/TableView/TableViewEditor.tsx
frontend-html/src/model/entities/WorkbenchLifecycle/KeyBuffer.ts
frontend-html/src/model/entities/WorkbenchLifecycle/WorkbenchLifecycle.ts
frontend-html/src/model/entities/types/IWorkbenchLifecycle.ts
frontend-html/src/model/selectors/getKeyBuffer.ts
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditor.tsx
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx
model-tests/model/Widgets/Menu/Menu.origam

The keys pressed before the CreateObject request finished were lost. When the user pressed insert and then continued to type fast.

FIX: Characters were lost when adding new row 2023.2

---

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateTimeEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/NumberEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/TagInputEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/TextEditor.tsx
frontend-html/src/gui/Workbench/ScreenArea/TableView/TableViewEditor.tsx
frontend-html/src/model/entities/WorkbenchLifecycle/KeyBuffer.ts
frontend-html/src/model/entities/WorkbenchLifecycle/WorkbenchLifecycle.ts
frontend-html/src/model/entities/types/IWorkbenchLifecycle.ts
frontend-html/src/model/selectors/getKeyBuffer.ts
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditor.tsx
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx
model-tests/model/Widgets/Menu/Menu.origam
test/tests_e2e/10_slowRequests.test.js
test/tests_e2e/modelIds.js

The keys pressed before the CreateObject request finished were lost. When the user pressed insert and then continued to type fast.

FIX: Characters were lost when adding new row

---

backend/Origam.Schema.MenuModel/SchemaItems/ModalDialogCloseType.cs
backend/Origam.Server/Common/ServerEntityUIActionRunnerClient.cs

In this new case will merge DataSet with constraints errors.

FEATURE: ModalDialogCloseType.CloseAndCommitWithErrors

---

frontend-html/src/gui/Components/ScreenElements/Table/Scrollee.tsx
frontend-html/src/gui/Components/ScreenElements/Table/SimpleScrollState.ts
frontend-html/src/gui/Components/ScreenElements/Table/Table.module.scss
frontend-html/src/gui/Components/ScreenElements/Table/Table.tsx
frontend-html/src/gui/Components/ScreenElements/Table/types.ts

FIX: Focusing filter controls does not scroll corresponding grid

---

backend/Origam.Server/Common/ServerEntityUIActionRunnerClient.cs

FIX: Invalid CloseType.None

---

backend/Origam.Server/Session Stores/WorkflowSessionStore.cs

if no notifications were defined in the model

FIX: Empty notification was shown on workflow screens

---

frontend-html/src/gui/Components/ScreenElements/Editors/DateCompleter.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateEditorModel.ts
frontend-html/src/tests/DateTimeCompleter.test.ts

if the editor format was set to "time"

FIX: Time editor value could not be changed 2022.3

---

frontend-html/src/gui/Components/ScreenElements/Editors/DateCompleter.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateEditorModel.ts
frontend-html/src/plugins/tools/PluginRegistration.ts
frontend-html/src/tests/DateTimeCompleter.test.ts

if the editor format was set to "time"

FIX: Time editor value could not be changed

---

build/build-monorepo.yaml

origam-html -> origam-server
origam-client -> origam-desktop-client

BUILD: Release assets names

---

frontend-html/src/gui/Workbench/ScreenArea/FormView/FormViewEditor.tsx
frontend-html/src/gui/connections/CScreenToolbar.tsx
frontend-html/src/gui/connections/MobileComponents/BottomToolBar/BottomToolBar.tsx
frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts
frontend-html/src/model/actions-ui/ScreenToolbar/saveButtonVisible.ts

if F5 was pressed right after making changes and before leaving the editor

 FIX: UpdateObject was not run before workflow next 2024.1

---

frontend-html/src/gui/Workbench/ScreenArea/FormView/FormViewEditor.tsx
frontend-html/src/gui/connections/CScreenToolbar.tsx
frontend-html/src/gui/connections/MobileComponents/BottomToolBar/BottomToolBar.tsx
frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts
frontend-html/src/model/actions-ui/ScreenToolbar/saveButtonVisible.ts

if F5 was pressed right after making changes and before leaving the editor

FIX: UpdateObject was not run before workflow next

---

frontend-html/src/model/actions-ui/ScreenTabHandleRow/onScreenTabCloseClick.ts
frontend-html/src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
frontend-html/src/model/entities/FormScreenLifecycle/QuestionCancelWorkflow.tsx

pressing workflow cancel and closing the workflow tab runs the same code now

FEATURE: User is asked to confirm workflow cancellation

---

frontend-html/src/model/entities/ApplicationLifecycle.tsx
frontend-html/src/oauth.ts

the user was logged out immediately after logging in

FIX: It was not possible to login after logging out

---

frontend-html/src/model/entities/ApplicationLifecycle.tsx
frontend-html/src/oauth.ts

the user was logged out immediately after logging in

FIX: It was not possible to login after logging out 2024.2

---

model-root/model/Security/FormControlSet/Security/UsersAndRoles.origam

Reverts origam/origam#2494, because it caused a breaking change and more needs to be done before this change is implemented.

Revert "FIX: Users screen had add and copy buttons enabled"

---

frontend-html/src/gui/connections/MobileComponents/Form/ComboBox/MobileDropdownBehavior.tsx
frontend-html/src/modules/Editors/DropdownEditor/Cells/TextCellDriver.tsx
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

When filtering in combobox, the matching text is highlighted in all filtered results. It should also work when filtering by special characters that are used in regular expressions.

UX: Highlight matching text when filtering in combobox

---

frontend-html/src/gui/Workbench/ScreenArea/FormView/BackupFocusPlaceHolder.module.scss
frontend-html/src/gui/Workbench/ScreenArea/FormView/BackupFocusPlaceHolder.tsx
frontend-html/src/gui/Workbench/ScreenArea/FormView/FormBuilder.tsx
frontend-html/src/model/entities/FormFocusManager.ts

FIX: Default action was not executed after pressing enter on empty modal window

---

frontend-html/src/gui/Workbench/ScreenArea/FormView/BackupFocusPlaceHolder.module.scss
frontend-html/src/gui/Workbench/ScreenArea/FormView/BackupFocusPlaceHolder.tsx
frontend-html/src/gui/Workbench/ScreenArea/FormView/FormBuilder.tsx
frontend-html/src/model/entities/FormFocusManager.ts
frontend-html/yarn.lock

FIX: Default action was not executed after pressing enter on empty modal window 2024.3

---

frontend-html/src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx

FIX: Filters not applied when changed twice (master)

---

frontend-html/src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx

FIX: Filters not applied when changed twice (2024.2)

---

frontend-html/src/gui/Workbench/ScreenArea/FormView/FormViewEditor.tsx
frontend-html/src/model/actions-ui/DataView/TableView/onFieldBlur.ts
frontend-html/src/model/actions/DataView/TableView/flushCurrentRowData.ts
frontend-html/src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx

as a result of that enter press. Works in forms only.

FEATURE: Default action is executed after enter press if no update was executed

---

frontend-html/src/gui/Workbench/ScreenArea/FormView/FormViewEditor.tsx
frontend-html/src/model/actions-ui/DataView/TableView/onFieldBlur.ts
frontend-html/src/model/actions/DataView/TableView/flushCurrentRowData.ts
frontend-html/src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx

as a result of that enter press. Works in forms only.

FEATURE: Default action is executed after enter press if no update was executed 2024.4

---

frontend-html/public/locale/localization_cs-CZ.json
frontend-html/public/locale/localization_de-CH.json
frontend-html/public/locale/localization_de-DE.json
frontend-html/public/locale/localization_en-US.json
frontend-html/public/locale/localization_fr-CH.json
frontend-html/src/gui/Components/ScreenElements/Table/Table.tsx
frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/cells/dataCell.ts
frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx
frontend-html/src/model/entities/TablePanelView/types/ITablePanelView.ts
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx

Adjusted the tooltip for MacOS users. Cursor behavior should now be also working with the Cmd key on Mac keyboard.

UX: Standardize cursor behavior on Mac

---

frontend-html/src/gui/connections/CScreenHeader.tsx

Fixed rendering buttons so that they don't appear in the screen header when a dialog screen is opened. Also fixed the form title not being rendered in the screen header.

FIX: Modal dialog buttons propagation

---

backend/Origam.OrigamEngine/ModelXmlBuilders/FormXmlBuilder.cs

Fixed selection boxes showing up when no action had MultipleCheckboxes mode.

FIX: Work queue screen shows selection checkboxes when command doesn't require it 2024.4

---

frontend-html/src/gui/Components/ScreenElements/Editors/TagInputEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Table/FilterSettings/HeaderControls/TagFilterEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Table/FilterSettings/HeaderControls/TagLookupFilterEditor.tsx
frontend-html/src/modules/DataView/DataViewData.ts
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorData.tsx
frontend-html/src/modules/Editors/DropdownEditor/TagInputEditorData.tsx

…resulted in record not saved error
Happened on MenuItems with the property RequestSaveAfterUpdate set to true.

FIX: Changes some times not saved after pressing enter in grid 2024.5

---

frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx

Fixed unexpected horizontal scrolling when new window opens up after Ctrl+click. Also fixed focus not moving to the Ctrl+clicked row.

FIX: Unexpected horizontal scrolling after Ctrl+click, focus not moving to selected row

---

frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx

Fixed unexpected horizontal scrolling when new window opens up after Ctrl+click. Also fixed focus not moving to the Ctrl+clicked row.

FIX: Unexpected horizontal scrolling after Ctrl+click, focus not moving to selected row 2024.5

---

frontend-html/src/gui/Components/Dropdown/Dropdown.module.scss
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx

Fixed the color of dropdown values if the value was not a link. Also fixed pointer-cursor and tooltip text showing when hovering over an empty dropdown, which may contain a link value.

FIX: Non link dropdown values have blue color

---

frontend-html/src/gui/Components/Dropdown/Dropdown.module.scss
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx

Fixed the color of dropdown values if the value was not a link. Also fixed pointer-cursor and tooltip text showing when hovering over an empty dropdown, which may contain a link value.

FIX: Non link dropdown values have blue color 2024.5

---

backend/Origam.DA.Service/MetaModelUpgrade/UpdateScriptContainers/XsltDataPageScriptContainer.cs
backend/Origam.Schema.GuiModel/Pages/XsltDataPage.cs
backend/Origam.Server/Pages/XsltPageRequestHandler.cs
model-root/model/Security/Page/adminuserRoles.origam
model-tests/model/Api/Page/apipublictest-api-body-input-data-page.origam
model-tests/model/Security/Page/adminuserRoles.origam
model-tests/model/Widgets/DataEntity/Widgets/AllDataTypes.origam
model-tests/model/Widgets/Page/LinkReportAPI.origam
model-tests/model/Widgets/Page/OmitJsonMainElement.origam

New flag OmitJsonMainElement provides possibility to remove main entity name from the JSON output.

FEATURE: XsltDataPage.OmitJsonMainElement

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

while the dropdown was visible

FIX: Focus lost after pressing tab twice fast in combobox 2024.5

---

backend/Origam.Workflow/WorkQueue/WorkQueueService.cs
model-tests/model/Root/DataStructure/Work Queue/WorkQueueEntry_MoveToErrorQueue.origam

if there was a DBConcurrencyException while trying to move them

FIX: Failed work queue entries were not moved to the error queue

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx
test/mssqlscript.sh

after clicking on a dropdown value and pressing tab quickly

FIX: Wrong dropdown value was sometimes selected 2024.7

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

after clicking on a dropdown value and pressing tab quickly

FIX: Wrong dropdown value was sometimes selected 2024.8

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

after clicking on a dropdown value and pressing tab quickly

FIX: Wrong dropdown value was sometimes selected

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

by highlighting the value with mouse and pressing delete or backspace.

FIX: Value in a read only combo box could be deleted  2024.7

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

by highlighting the value with mouse and pressing delete or backspace.

FIX: Value in a read only combo box could be deleted 2024.8

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

by highlighting the value with mouse and pressing delete or backspace.

FIX: Value in a read only combo box could be deleted 

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

clicking on dropdown item when editing a combobox value and pressing tab fast after that

FIX: Focus lost after click and tab 2024.7

---

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx

clicking on dropdown item when editing a combobox value and pressing tab fast after that

FIX: Focus lost after click and tab 2024.8

---

backend/Origam.Workflow/WorkQueue/WorkQueueService.cs
backend/Origam.Workflow/WorkQueue/WorkQueueUtils.cs

FIX: WorkQueueService.WorkQueueGetMessage used message id as work queue id

---

backend/Origam.Workflow/WorkQueue/WorkQueueService.cs

because Concurrency exception was not handled

FIX: Work queue entry did not end up in the error queue 2024.8

---

backend/Origam.Workflow/WorkQueue/WorkQueueService.cs

because Concurrency exception was not handled

FIX: Work queue entry did not end up in the error queue

---

frontend-html/src/xmlInterpreters/screenXml.ts

if there was no screen configuration

FIX: Screen failed to load if grid configuration was missing

---

backend/Origam.Workflow/WorkQueue/WorkQueueService.cs
model-root/model/Root/DataStructure/Work Queue/WorkQueueEntry_MoveToErrorQueue.origam

because Concurrency exception was not handled

FIX: Work queue entry did not end up in the error queue 2024.7

---

backend/Origam.Server/Controller/SessionController.cs

DEV: Build warning removed

---

backend/Origam.Server/Controller/AbstractController.cs

was included in the http response when a validation exception occured

FIX: Stack trace was shown in production environment 2024.9

---

backend/Origam.Server/Pages/UserApiProcessor.cs

it was replaced with a generic error message instead. Only happened in production environment

FIX: Error message was not returned from model api

---

backend/Origam.Server/Pages/UserApiProcessor.cs

it was replaced with a generic error message instead. Only happened in production environment

FIX: Error message was not returned from model api 2024.9

---

frontend-html/src/gui/Components/ScreenElements/Editors/DateCompleter.tsx
frontend-html/src/tests/DateTimeCompleter.test.ts

when the date editor format was d. MMMM yyyy HH:mm

FIX: It was not possible to set time other than 00:00

---

frontend-html/src/gui/Components/ScreenElements/Editors/DateCompleter.tsx

when the date editor format was d. MMMM yyyy HH:mm

FIX: It was not possible to set time other than 00:00 2024.9

---

backend/Origam.BI.CrystalReports.NetFx/CrystalReportService.cs
backend/Origam.BI.FastReport/FastReportService.cs
backend/Origam.BI/ReportHelper.cs
backend/Origam.Common/LanguageSwitcher.cs
backend/Origam.Server/Controller/ReportController.cs
backend/Origam.Workbench.Services/CoreServices/ReportService.cs
backend/Origam.Workflow/Service Agents/ReportServiceAgent.cs

- breaking change - fast reports are only loaded from report folder specified in OrigamSettings file

DEV: Report infrastructure refactoring

---

backend/OrigamArchitect/SchemaCompareEditor.cs

ended with object reference exception in Architect

FIX: Deployment scripts could not be generated

---

backend/OrigamArchitect/SchemaCompareEditor.cs

ended with object reference exception in Architect

FIX: Deployment script generation 2024.9

---

backend/OrigamArchitect/SchemaCompareEditor.cs

ended with object reference exception in Architect

deployment-script-generation-2024-8

---

backend/Origam.Common/HttpTools.cs
backend/Origam.Common/LanguageSwitcher.cs
backend/Origam.Common/Origam.Common.csproj
backend/Origam.Workflow/Origam.Workflow.csproj
backend/Origam.Workflow/WorkQueue/WorkQueueThrottle.cs

caused confusing warnings. Refactoring would be too extensive

DEV: Nullable annotations removed

---

backend/Origam.Schema.MenuModel/SchemaItems/FormReferenceMenuItem.cs
backend/Origam.Server/ServerCoreUIService.cs
model-tests/model/Widgets/DataEntity/Widgets/WidgetSectionTestDetail.origam
model-tests/model/Widgets/DataEntity/Widgets/WidgetSectionTestMaster.origam

Action on other entity than list entity in lazily loaded screen can be of any merge type.

FEATURE: Eased multiple checkboxes action restriction

---

model-root/model/Root/DeploymentVersion/_origam_root/4.14.origam___commandText___827c6068-12e8-47fc-8b25-f255d3f0170c.txt
model-tests/model/Root/DeploymentVersion/_origam_root/4.14.origam___commandText___827c6068-12e8-47fc-8b25-f255d3f0170c.txt

FIX: Language table contained "Ceština" in the czech language name instead of "Čeština"

---

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateTimeEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/NumberEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/TagInputEditor.tsx
frontend-html/src/gui/Components/ScreenElements/Editors/TextEditor.tsx
frontend-html/src/modules/DataView/DataViewData.ts
frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx

leading to confusing/wrong results

UX: Preventing drag and drop values between inputs on form

---

frontend-html/src/model/actions/Workbench/openScreenByReferenceAndLookup.ts
frontend-html/src/model/actions/Workbench/openScreenIgnoreSelectionDialog.ts
frontend-html/src/model/entities/DataView.ts

when opening a search result with a selection dialog

FIX: Selection dialog was not ignored when clicking on search result 2024.9

---

.github/workflows/integration-tests.yml
.github/workflows/nunit-tests.yml
frontend-html/src/model/actions/Workbench/openScreenByReferenceAndLookup.ts
frontend-html/src/model/actions/Workbench/openScreenIgnoreSelectionDialog.ts
frontend-html/src/model/entities/DataView.ts

when opening a search result with a selection dialog

FIX: Selection dialog was not ignored when clicking on search result 2024.10

---

backend/Origam.OrigamEngine/ModelXmlBuilders/FormXmlBuilder.cs

leading to confusing behavior on front end

FIX: It was possible to bind color editor to a field of type other than integer

---

frontend-html/src/model/entities/getAllLookupIds.tsx

FIX: Checklist filter options could not be fetched if another filter was active 2024.9

---

frontend-html/src/model/entities/getAllLookupIds.tsx

FIX: Checklist filter options could not be fetched if another filter was active 2024.10

---

frontend-html/src/model/entities/getAllLookupIds.tsx

FIX: Checklist filter options could not be fetched if another filter was active 2024.11

---

frontend-html/src/gui/Workbench/ScreenArea/FormView/FormViewEditor.tsx
frontend-html/src/model/actions-ui/DataView/TableView/onFieldBlur.ts
frontend-html/src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
frontend-html/src/model/entities/types/IFormScreenLifecycle.ts
frontend-html/src/model/selectors/DataSources/getChangedColumns.ts

by evaluating function fields, executing rules...

UX: Default action is only executed on enter if the server did not change additional fields

---

backend/Origam.Schema/ItemCollection/ArchitectSchemaItemCollection.cs

if the fields had Inheritable set to True

FIX: Moving of fields to different package was failing

---

backend/Origam.workflow.mail/Origam.workflow.mail.csproj
backend/Origam.workflow.mail/WorkQueueImapLoaderAdapter.cs

* MimeKit 4.9.0
* refactoring
* detection of XML invalid characters to prevent complete failure of load operation
* sanitization parameter - if true invalid XML characters are removed from the mail body, otherwise the mail is put to badmail folder

FEATURE: IMAP Loader Improvements

---

build/build-monorepo.yaml

Adapting build infrastructure to produce Origam Scheduler .NET80.

BUILD: Origam Scheduler .NET80 

---

backend/Origam.OrigamEngine/ModelXmlBuilders/AsPanelActionButtonBuilder.cs
backend/Origam.OrigamEngine/ModelXmlBuilders/FormXmlBuilder.cs
backend/Origam.Server/Session Stores/SelectionDialogSessionStore.cs
frontend-html/src/model/entities/Action.ts
frontend-html/src/model/entities/types/IAction.ts
frontend-html/src/xmlInterpreters/screenXml.ts

FIX: Work queue commands were disappearing after clicking on select all checkbox 2025.2

---

backend/Origam.Server/CoreHttpTools.cs

FIX: Attachment file name contained "+" characters

---

backend/Origam.Workflow/Engine.cs
backend/Origam.Workflow/Tasks/ForEachBlockEngineTask.cs
model-tests/model/Widgets/Menu/Menu.origam

* Added extra logging to gather more info on NullReferenceException that is sometimes thrown
* Added ForEach test
* Potential NullReferenceException fix

DEV: Added logging to help fix a NullReferenceException

---

backend/Origam.Workflow/Service Agents/ModelServiceAgent.cs

* fields in views and virtual entites are not in the result set
* fields specified in interface are present in result set for all inheriting entities
* refactoring
https://support.advantages.cz/t/dokumentace-databazove-struktury/3116

FEATURE: Improvements in db structure documentation

---

README.md

- fix typo "PIE-HTTML" -> "PIE-HTML" in README
- `yarn test` *(fails: connect EHOSTUNREACH)*

DEV: Correct image caption

---

backend/Origam.Gui/WorkflowCallbackHandler.cs
backend/Origam.Workflow/Tasks/ForEachBlockEngineTask.cs
model-tests/model/Widgets/Workflow/Widgets/CallWorkflowInForEachStep.origam
model-tests/model/Widgets/Workflow/Widgets/CallWorkflowWithForEach.origam
model-tests/model/Widgets/Workflow/Widgets/ForEachTest.origam
model-tests/model/Widgets/Workflow/Widgets/UpdateText2.origam

Steps following the for each block aren't executed.
Complex workflows are loosing user context.
As a temporerary solution I'm reverting #3141. I've also extended workflow samples in model-test.

FIX: Workflows with for each step don't work properly

---

.gitignore
backend/.gitignore

Update `.gitignore` file to exclude `Origam.Architect.Server` development settings file.
https://discord.com/channels/913379881012830228/913729189805457438/1403395499436015756
https://discord.com/channels/913379881012830228/1404386038344060969/1405153892320411682

DEV: Update .gitignore file

---

architect-html/src/components/editors/GetEditor.tsx
architect-html/src/components/editors/codeEditor/CodeEditor.module.scss
architect-html/src/components/editors/codeEditor/CodeEditor.tsx
architect-html/src/components/editors/xsltEditor/XsltEditor.tsx

* Refactor CodeEditor into reusable component.
* Add support for Vim mode to CodeEditor.

FEATURE: Add Vim mode

---

backend/Origam.BI.Excel/ExcelService.cs
backend/Origam.BI.Excel/Origam.BI.Excel.csproj
backend/Origam.Excel/Origam.Excel.csproj
backend/Origam.Server/Origam.Server.csproj
backend/Origam.Workflow.FileService/Origam.Workflow.FileService.csproj
backend/OrigamArchitect/OrigamArchitect.csproj

to solve a security problem with ImageSharp

DEV: Upgraded ImageSharp and NPOI

---

architect-html/src/stores/UiState.ts

Enhances the loading of states from local storage by adding checks for null or empty values and validating the parsed data. This prevents errors and ensures default values are returned when appropriate.

FIX: Local storage initial state
