origam/origam

backend/Origam.DA.Service/DatasetTools.cs, backend/Origam.Rule/RuleEngine.cs
- New parameter enforceNullValues allows setting null values into the mandatory fields when row state is added.
- The new setting is used during rules resolution.
=> CHG: CopyRecordValues

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBody.tsx, frontend-html/yarn.lock
also, the dropdown width did not account for vertical scroll bar width and cell padding hiding part of the widest cell text
=> FIX: Dropdown height was not limited to 6 lines

backend/Origam.Security.Common/IManager.cs, backend/Origam.Security.Identity/IdentityServiceAgent.cs, backend/Origam.Security.NetFx/AspNetManagerAdapter.cs, backend/Origam.ServerCore/Authorization/CoreManagerAdapter.cs
- token's purpose was `Confirmation` instead of `ResetPassword`
=> FIX: Invalid tokens for password reset

backend/Origam.Services/IParameterService.cs, backend/Origam.Workbench.Services/ParameterService.cs, backend/OrigamArchitect/ArchitectWorkbench.cs
Data constant/parameter not found.
Parameter name: id
Actual value was 9e301a8b-b356-42fa-ae57-3be3a28650d7.
=> Architect throw exception when is Disconnected.

backend/Origam.Server/Configuration/IdentityServerConfig.cs, backend/Origam.Server/Startup.cs, backend/Origam.Server/TemplateFiles/_appsettings.json
defaults: "CookieExpirationMinutes": 60, "CookieSlidingExpiration": true
=> NEW: Cookie lifetime can be set in the appsettings.json

backend/Origam.Server/IdentityServerGui/Account/AccountController.cs
Added exception when reset password mail is old version.
=> Added log information when a password reset.

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor.module.scss
if the date input was too short
=> FIX: Calendar widget was overlaid with the date text

model-root/model/Security/Workflow/Security/IDENTITY_USER_MANAGEMENT/Identity_DeleteUser.origam
- fixed order of steps in the worklow
=> FIX: Remove User Access - Username not found in membership database.

frontend-html/src/model/entities/Searcher.ts
pressing enter in empty search input opened the last search result
=> FIX: Search results were not cleared after closing the search window

backend/Origam.ReflectorCache/ReflectorCache.cs, backend/Origam.Schema.WorkflowModel/SchemaItems/AbstractWorkflowBlock.cs, backend/Origam.Schema.WorkflowModel/SchemaItems/Workflow.cs, backend/Origam.Schema.WorkflowModel/SchemaItems/WorkflowTasks/AcceptContextStoreChangesTask.cs, backend/Origam.Workflow/Tasks/AcceptContextStoreChangesEngineTask.cs, backend/Origam.Workflow/WorkflowTaskFactory.cs
https://community.origam.com/t/workflow-task-accept-context-store-changes/1793
=> Accept Changes Worfklow Task

frontend-html/src/gui/Components/WorkflowFinishedPanel/WorkflowFinishedPanel.module.scss
the font size was 48, should be 16
=> FIX: Default workflow end message font size was not applied

backend/Origam.DA.Service/MsSqlDataService.cs, backend/Origam.DA.Service/PgSqlDataService.cs, backend/OrigamArchitect/App.config, backend/OrigamSetup/ArchitectSetup.wxs, backend/OrigamSetup/build-msi.bat, backend/OrigamSetup/build-msi.ps1, backend/OrigamSetup/config/OrigamArchitect.exe.config
1. Postgresql => Create New Project on PostgresSQL database terminated in ERROR:
https://community.origam.com/t/origam-architect-create-new-project-with-postgressql-database-fail-on-missing-system-numeric-vectors-dll/1735/6
* By fixing this issue, I have found on my local postgresql installation that user <dbname> which has been created by installation is not removed in case if the create new project fails (rollback didn't work because in my database there was no user postgres). I fixed this by updating a script for rollback.
2. Postges + MS SQL:
* New project could not be created because of failing step **Create new Web User** => there was remove of column `IsLockedOut` column in the model but this column remained in `CreateOrigamUserInsert` in both adapters - MS SQL and Postgres
Note:
I …
=> Fix of Origam Architect for PostgresSql:

backend/Origam.DA.Service/MsSqlDataService.cs, backend/Origam.DA.Service/PgSqlDataService.cs, backend/OrigamArchitect/App.config, backend/OrigamSetup/ArchitectSetup.wxs, backend/OrigamSetup/build-msi.bat, backend/OrigamSetup/build-msi.ps1, backend/OrigamSetup/config/OrigamArchitect.exe.config
* Fix of Origam Architect:
1. Postgresql => Create New Project on PostgresSQL database terminated in ERROR:
https://community.origam.com/t/origam-architect-create-new-project-with-postgressql-database-fail-on-missing-system-numeric-vectors-dll/1735/6
* By fixing this issue, I have found on my local postgresql installation that user <dbname> which has been created by installation is not removed in case if the create new project fails (rollback didn't work because in my database there was no user postgres). I fixed this by updating a script for rollback.
2. Postges + MS SQL:
* New project could not be created because of failing step **Create new Web User** => there was remove of column `IsLockedOut` column in the model but this column remained in `CreateOrigamUserInsert` in both adapters - …
=> Fix of Origam Architect for PostgresSql: (#730)

backend/Origam.Server/Views/Account/Login.cshtml
- external sign-in buttons have id in form `loginButton-AuthenticationScheme`, where `AuthenticationScheme` is `Google`, `Microsoft` or `AzureAd`.
=> NEW: Login Screen External Sign-in Button Id

backend/Origam.Server/Controller/UIServiceController.cs, frontend-html/src/model/entities/OrigamAPI.ts
seemed more appropriate because state on the server is changed and nothing is returned
=> INTERNAL: DestroyUI call type changed to post

backend/Origam.Schema.WorkflowModel/WorkflowHelper.cs
A persisting of a new sort set and sort set item caused model item cache invalidation and removal of field OldPrimaryKey. The field is crucial for a corret run of UpdateReference() after cloning.
=> #2529 Fix cloning process when creating a WQ from entity

frontend-html/src/model/actions-ui/DataView/onCopyRowClick.ts, frontend-html/src/model/actions-ui/DataView/onCreateRowClick.ts, frontend-html/src/model/entities/FilterConfiguration.ts
…ers were active led to filters to be closed and grid to be reloaded
which caused active row to be switched to the first row because the dirty row was not returned by the GetRows call. This caused an error on the server.
=> FIX: Filter UI conflict with add/copy row

backend/Origam.OrigamEngine/ModelXmlBuilders/FormXmlBuilder.cs
If there was a column with Id "Id" in a grid and the user edited its width, it was not saved because the column was duplicated in the screen XML (initUi)
=> FIX: Column width was not saved

backend/Origam.OrigamEngine/ModelXmlBuilders/AsPanelBuilder.cs, backend/Origam.OrigamEngine/ModelXmlBuilders/FormXmlBuilder.cs, frontend-html/src/model/actions/DataView/TableView/saveColumnConfigurations.ts, frontend-html/src/model/entities/Property.ts, frontend-html/src/model/entities/types/IProperty.ts, frontend-html/src/xmlInterpreters/screenXml.ts
if the Id column was made visible in the underlaying entity
=> FIX: First grid column was not visible

backend/Origam.Server/Views/Shared/_Layout.cshtml, build/build-monorepo.yaml
- static files are requested with version parameter, where version id is equal to build id, in order to prevent problems with caching static files between versions
=> Identity GUI

frontend-html/src/model/actions/handleError.tsx
I found an unused localization string "network_unavailable": "Network Unavailable" so I used it. I would probably use a different formulation, but since this one was ok before I guess it is ok now. @tvavrda Is it ok?
=> FIX: AxiosError was shown to the user

backend/Origam.Security.Identity/IdentityServiceAgent.cs, backend/Origam.Workflow/Tasks/ServiceMethodCallEngineTask.cs
* FIX: IdentityServiceAgent methods didn't work from workflows triggered from automatic work queue processing
* INTERNAL: Simplify IDisposable pattern for IdentityServiceAgent
* INTERNAL: Refactoring
---------
Co-authored-by: Vaclav Urbanek <vaclav.urbanek@advantages.cz>
=> FIX: IdentityServiceAgent methods not available in work queues (#1351)

backend/Origam.Schema.EntityModel/SchemaItems/FunctionCall.cs
- It wasn't possible to create a new function field in Architect, because the new type rules were incorrectly defined.
=> FIX: Unable to create function field

backend/Origam.Server/Controller/DeepLinkController.cs, backend/Origam.Server/Model/DeepLink/GetDeepLinkMenuInput.cs
GetDeepLinkMenuInput.ReferenceId type changed from Guid to object, because it was limiting underlying calls to IDataLookupService.GetMenuBinding.
=> DEV: DeepLinkController

backend/Origam.Rule/ResourceTools.cs, backend/Origam.Rule/RuleEngine.cs, backend/Origam.Rule/XsltFunctions/XsltFunctionContainerFactory.cs, backend/OrigamArchitect/DebugInfo.cs
* Properties did not initialize.
* INTERNAL: ResourceTools refactored it was decided that it would be better to make all dependencies external
=> FIX: AS:ResourceIdByActiveProfile() throws object reference not set

backend/Origam.Schema.EntityModel.UI/Wizards/CreateForeignKeyCommand.cs, backend/Origam.UI/WizardForm/Wizard.Designer.cs, backend/Origam.UI/WizardForm/Wizard.cs
The Create Foreign key wizard did not save a new field automatically. The wizard did not detect a option of Checkbox "AllowNull".
=> FIX: Create Foreign key wizard ignored AllowNull field

backend/Origam.Schema.EntityModel.UI/Wizards/CreateForeignKeyCommand.cs, backend/Origam.UI/WizardForm/Wizard.Designer.cs, backend/Origam.UI/WizardForm/Wizard.cs
The Create Foreign key wizard did not save a new field automatically. The wizard did not detect an option of Checkbox "AllowNull".
=> FIX: Create Foreign key wizard ignored AllowNull field (#1560)

backend/Origam.Gui.Win/FormGenerator.cs
Screen section setting 'DisableActionButtons' was ignored in Origam desktop client.
=> FIX duplication of action buttons in Origam desktop client

backend/Origam.Server/Controller/AbstractController.cs
…when building query for GetRows() ui enpoint (get list for lazily loaded screens).
=> Cant set blob column in lazily loaded screens with iswriteonly true

backend/Origam.Server/Controller/AbstractController.cs
Approach to IsWriteOnly fields similar to detached fields when building query for GetRows() ui endpoint (get list for lazily loaded screens).
=> FIX: Write-only blob column doesn't work in lazily loaded screen

frontend-html/src/model/actions/Global/onRootElementClick.ts
when the generated <a/> element contained some inner html. Not just a string.
=> FIX: Deep link was not working

frontend-html/src/gui/Components/ScreenElements/Editors/ColorEditor.tsx
This was reported as the ColorPicker was unable to be edited by any input fields in grid view but works correctly in form view.
Further investigations revealed that the field is actually broken in both grid and form views and the main issue is an infinite loop of ColorPicker wasted renders. The exact mechanism of why that only caused the editing issue in grid views and not form views remains unknown, expectation is rather being not properly editable in both, I suspect the difference in details of how the focusing works in grid and form views, which caused any internal color picker input field getting the focus stolen each render in grid view and not in form view.
The infinite loop was present because of an unstable function reference passed to div element. Rough loop description follows: …
=> FIX: Color picker rendering flaw

backend/Origam.DA.Service/AbstractSqlDataService.cs, backend/Origam.DA.Service/Generators/DatasetGenerator.cs
* Improved logging of concurrency exception 
* Added null->empty string awareness, list changes even when an event workflow changes the data (before rollbacking the change), excluded data structure fields from fields causing marking a record as updated.
=> FIX: Empty concurrency exception

backend/Origam.DA.Service/AbstractSqlDataService.cs, backend/Origam.DA.Service/Generators/DatasetGenerator.cs
* Improved logging of concurrency exception 
* Added null->empty string awareness, list changes even when an event workflow changes the data (before rollbacking the change), excluded data structure fields from fields causing marking a record as updated.
Co-authored-by: Vaclav Urbanek <vaclav.urbanek@advantages.cz>
=> FIX: Empty concurrency exception (#1689)

frontend-html/src/model/actions-ui-tree/actions.ts, frontend-html/src/model/entities/OrigamAPI.ts, frontend-html/src/model/entities/types/IApi.ts, frontend-html/src/model/entities/types/IDataView.ts
* Allow intercepting actions before potential error is handled in a dialog. 
* Provide blob url (e.g. to be used as iframe src).
* Improve types to make focusFormViewControl accessible in IDataView interface.
=> FEATURE: Improve plugin infrastructure

frontend-html/src/gui/connections/CScreenToolbar.tsx, frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts, frontend-html/src/utils/keyShortcuts.ts
Pressing the save shortcut did not result in sending the active field data to the server
=> FIX: Save keyboard shortcut didn't persist focused field contents

backend/OrigamSetup/ArchitectSetup.wxs
NPOI.dll was renamed to NPOI.Core.dll
=> FIX: Build of setup failed due to recent dll bump

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx
Last valid dropdown value was selected after pressing enter even though the current text in the input resulted in no valid values in the dropdown
=> FIX: Invalid option used in lookup with emptied dropdown

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts, frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx, frontend-html/src/model/entities/TablePanelView/types/ITablePanelView.ts
Unmounting an editor during scroll was accidentally disabled when fixing another problem.
=> FIX: Editor remains mounted when scrolling

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts, frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx, frontend-html/src/model/entities/TablePanelView/types/ITablePanelView.ts
Unmounting an editor during scroll was accidentally disabled when fixing another problem.
=> FIX: Editor remains mounted when scrolling (2022.4)

backend/Origam.Server/Session Stores/FormSessionStore.cs
=> FIX: Save button was not visible 2022.4

frontend-html/src/gui/connections/CScreenHeader.tsx, frontend-html/src/model/entities/DataView.ts, frontend-html/src/model/entities/RowState.ts
so it was not clear that the displayed data was not in final state during scrolling
=> FIX: Busy indicator was not active right after row states were requested 2022.4

frontend-html/package.json, frontend-html/yarn.lock
Safari browser does not support lookbehind operator until version 16.4.
=> FIX: Upgrade @origam/utils to fix unsupported regex in older Safari (2022.4)

frontend-html/package.json, frontend-html/yarn.lock
Safari browser does not support lookbehind operator until version 16.4.
=> FIX: Upgrade @origam/utils to fix unsupported regex in older Safari (master)

backend/Origam.Gui.Win/AsPanel.cs, backend/Origam.Gui.Win/Grid/AsCheckStyleColumn.cs, backend/Origam.Gui.Win/Grid/AsTextStyleColumn.cs, backend/Origam.Gui.Win/Grid/DataGridBlobColumn.cs, backend/Origam.Gui.Win/Grid/DataGridBuilder.cs, backend/Origam.Gui.Win/Grid/DataGridDropdownColumn.cs, backend/Origam.Gui.Win/Grid/DataViewColumn.cs, backend/Origam.Rule/RowSecurityStateBuilder.cs, backend/Origam.Rule/RuleEngine.cs, backend/Origam.Server/Common/UIManager.cs, backend/Origam.Server/Pages/XsltPageRequestHandler.cs, backend/Origam.Server/Session Stores/SessionStore.cs
Improved row state evaluation on a complex lazily loaded screens.  Refactored RowSecurityState building process  - separated into a new class RowSecurityStateBuilder.  Optimization - build only what is needed for all callers.
=> FIX: Improve row state evaluation on a complex lazily loaded screens

frontend-html/src/model/entities/DataViewLifecycle/DataViewLifecycle.ts
some of the reactions were not fired after opening the form leading to missing data. The reactions were fired after pressing screen refresh.
=> FIX: GetData was not called in a complex form 2022.4

frontend-html/src/model/entities/DataViewLifecycle/DataViewLifecycle.ts
some of the reactions were not fired after opening the form leading to missing data. The reactions were fired after pressing screen refresh.
=> FIX: GetData was not called in a complex form

frontend-html/src/model/entities/DataViewLifecycle/DataViewLifecycle.ts
some of the reactions were not fired after opening the form leading to missing data. The reactions were fired after pressing screen refresh.
=> FIX: GetData was not called in a complex form 2023.1

backend/Origam.Server/IApplicationBuilderExtensions.cs, backend/Origam.Server/Middleware/OptionalTokenAuthenticationMiddleware.cs, backend/Origam.Server/Middleware/UserApiTokenAuthenticationMiddleware.cs
authorization should be optional
=> FIX: Authentication in work queue api made optional 2022.4

backend/Origam.Rule/RowSecurityStateBuilder.cs, backend/Origam.Rule/RuleEngine.cs, backend/Origam.Rule/RuleEvaluationCache.cs, backend/Origam.Server/Controller/SessionController.cs, backend/Origam.Server/Session Stores/SaveableSessionStore.cs, backend/Origam.Server/Session Stores/SessionStore.cs
* call rowstates in the final UpdateObject() method, not from UpdateObject() coming from doing dependency field reseting
* compute and remember a row-level-security result for a security type (read, write, etc) and column which doesn’t have any rule and apply it for all the further columns without any field-level-row-level security rule
* compute and cache a row-level-security rule result for a current row and use cached value whenever it’s needed again
=> FEATURE: Optimize datastructure rule evaluation

model-root/model/Root/DeploymentVersion/_origam_root/5.3.origam___commandText___f92c7cc1-f0c9-41da-a148-3bd3f769b8ad.txt, model-tests/model/Root/DeploymentVersion/_origam_root/5.3.origam___commandText___f92c7cc1-f0c9-41da-a148-3bd3f769b8ad.txt
The deployment scripts required following languages to be present in table `Language`: `de-DE`, `de-CH`, `cs-CZ`.
=> FIX: Localization deployment script failure

frontend-html/src/model/entities/FilterConfiguration.ts, frontend-html/src/model/entities/ListRowContainer.ts, frontend-html/src/model/entities/types/IFilterConfiguration.ts
no values were filled in the filters. Happened on an eagerly loaded screen with 10000 rows. The operations took about 10 sec.
=> FIX: Adding/deleting a row took a long time when the filters were open 2022.4

frontend-html/src/model/entities/FilterConfiguration.ts, frontend-html/src/model/entities/ListRowContainer.ts, frontend-html/src/model/entities/types/IFilterConfiguration.ts
no values were filled in the filters. Happened on an eagerly loaded screen with 10000 rows. The operations took about 10 sec.
=>  FIX: Adding/deleting a row took a long time when the filters were open 2023.1

frontend-html/src/model/entities/FilterConfiguration.ts, frontend-html/src/model/entities/ListRowContainer.ts, frontend-html/src/model/entities/types/IFilterConfiguration.ts
no values were filled in the filters. Happened on an eagerly loaded screen with 10000 rows. The operations took about 10 sec.
=> FIX: Adding/deleting a row took a long time when the filters were open

frontend-html/src/model/entities/ListRowContainer.ts
if there was more than one row in the grid already
=> FIX: Escape did not delete the just inserted row

frontend-html/src/gui/Workbench/ScreenArea/TableView/ResolveCellAlignment.tsx, frontend-html/src/gui/Workbench/ScreenArea/TableView/TableViewEditor.tsx, frontend-html/src/gui/connections/MobileComponents/Form/ComboBox/ComboBox.tsx, frontend-html/src/modules/Editors/DropdownEditor/Cells/HeaderCell.tsx, frontend-html/src/modules/Editors/DropdownEditor/Cells/TextCellDriver.tsx, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditor.tsx, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBody.tsx, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorSetup.tsx, frontend-html/src/modules/Editors/DropdownEditor/DropdownTableModel.ts
* Editor dropdown was not aligned when in first column in a grid
* Dropdown width increased by custom padding
* Redundant vertical scroll bar was sometimes rendered in dropdown
* Parameters made optional
(cherry picked from commit a000eecfee5ea89183e8d826ea7ebd0923a8b684)
=> FIX: Dropdown alignment 2023 1

frontend-html/src/gui/Workbench/ScreenArea/TableView/ResolveCellAlignment.tsx, frontend-html/src/gui/Workbench/ScreenArea/TableView/TableViewEditor.tsx, frontend-html/src/gui/connections/MobileComponents/Form/ComboBox/ComboBox.tsx, frontend-html/src/modules/Editors/DropdownEditor/Cells/HeaderCell.tsx, frontend-html/src/modules/Editors/DropdownEditor/Cells/TextCellDriver.tsx, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditor.tsx, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBody.tsx, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorSetup.tsx, frontend-html/src/modules/Editors/DropdownEditor/DropdownTableModel.ts
* Editor dropdown was not aligned when in first column in a grid
* Dropdown width increased by custom padding
* Redundant vertical scroll bar was sometimes rendered in dropdown
* Parameters made optional
(cherry picked from commit a000eecfee5ea89183e8d826ea7ebd0923a8b684)
=> FIX: Dropdown alignment 2022 4

frontend-html/src/gui/connections/CScreen.tsx, frontend-html/src/model/entities/OrigamAPI.ts, frontend-html/src/model/entities/types/IApi.ts
revert of: Indirect iframe content loading reverted (#2006) - and fixing it the way it worked
=> FIX: Loading reports in iframe fails

frontend-html/src/model/actions-ui/DataView/TableView/onTableKeyDown.ts
because the active column was not visible while no editor was open
=> FIX: Left and right arrows in grid disabled 2023.1

frontend-html/src/model/actions-ui/DataView/TableView/onTableKeyDown.ts
because the active column was not visible while no editor was open
=> FIX: Left and right arrows in grid disabled

backend/Origam.DA.Service/Generators/AbstractSqlCommandGenerator.cs, backend/Origam.DA.Service/Generators/MsSqlRenderer.cs, backend/Origam.DA.Service/Generators/PgSqlRenderer.cs, backend/Origam.DA.Service/Generators/SqlRenderer.cs
because the SQL behind it applied the filter on the ids instead of the lookup values. The time rendered in the SQL was also wrong, not respecting culture and formatting of the values from UIService/GetLookupLabelsEx (that is what is displayed in the grid).
=> FIX: Contains filter on lookup column returned too many values 2023.1

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts
when pressing "insert" in a grid editor after changing the editor value
=> FIX: Update was some times not send after pressing insert in a grid editor 2023.1

backend/Origam.Server/Middleware/ReturnOldDotNetAssemblyReferencesInSoapMiddleware.cs
When ExpectAndReturnOldDotNetAssemblyReferences=true in application.json 
Co-authored-by: Václav Urbánek <vaclav.urbanek@advantages.cz>
=> FIX: Soap service endpoint doesn’t return a valid content length

backend/Origam.Rule/DatasetRuleHandler.cs
Do not handle dataset RecordChange event for dataset commit actions. It handled all the DS rules and checks dataset from AcceptChanges() for each row during UpdateData() after SQL is already done.
=> FIX: Dataset RecordChange event for handled commit actions

backend/Origam.Rule/IndexedRuleQueue.cs
Deleting rows crashed the new indexed rule queue
because it was not possible to retrieve a primary key from an added and subsequently deleted row. Using a row's hashcode instead of a primary key solves this problem.
=> FIX: Deleting a just added row caused a crash

backend/Origam.Rule/DatasetRuleHandler.cs, backend/Origam.Server/Session Stores/SessionStore.cs
* FIX: Querying row states was executing rule engine without a reason on lazy-loaded screens
* FIX: Reverted UpdateObject optimizations - rules were not recalculated on parent/child entities
=> FIX: Rule engine fixes

backend/Origam.Rule/RuleEngine.cs, backend/Origam.Rule/Xslt/CompiledXsltEngine.cs, backend/Origam.Schema.EntityModel/Data Structure/DataStructureRule.cs, backend/Origam.Schema.EntityModel/Data Structure/DataStructureRuleSet.cs, backend/Origam.Workflow/ProfilingTools.cs
* FIX: Fetching entity name while processing rules caused some delays with rule/data intensive processes
* FIX: Server could hard crash sometimes when workflow measured execution failed
* DEV: It could happen to a rule queue to fail, an exception is logged now
* FIX: Remove Mvp XslCompiledTransform, it caused unstable behaviour at XmlNameTable (infinite loop)
=> FIX: Remove mvp and rule engine stabilization fixes (#2188)

backend/Origam.Workflow/WorkQueue/WorkQueueWorkflowLoader.cs
FIX: Work queue loader now returns 0 items when only one (empty) node e.g. <ROOT/> is returned from a loader workflow
=> FIX: Empty work queue entry when loader worflow returns empty ROOT element

backend/Origam.Server/Controller/AbstractController.cs, frontend-html/src/model/actions-ui/RecordInfo/onRecordInfoClick.ts, frontend-html/src/model/actions-ui/onSelectedRowChange.ts, frontend-html/src/model/entities/RecordInfo.ts, frontend-html/src/model/entities/types/IApi.ts, frontend-html/src/model/entities/types/IRecordInfo.ts
i.e. row has just been created but not saved yet
=> FIX: Record info was not displayed for new rows

backend/Origam.Server/Model/UIService/WorkflowNextInput.cs, backend/Origam.Server/ServerCoreUIService.cs, backend/Origam.Server/Session Stores/FormSessionStore.cs, backend/Origam.Server/Session Stores/ParameterSessionStore.cs, backend/Origam.Server/Session Stores/SaveableSessionStore.cs, backend/Origam.Server/Session Stores/SelectionDialogSessionStore.cs, backend/Origam.Server/Session Stores/SessionStore.cs, backend/Origam.Server/Session Stores/WorkQueueSessionStore.cs, backend/Origam.Server/Session Stores/WorkflowSessionStore.cs
…te an action when long running UpdateObject was still processing. Without lock protection it led to unpredictable results.
=> FIX: Possible to invoke ExecuteAction while UpdateObject was running

frontend-html/src/gui/Workbench/ScreenArea/TableView/TableViewEditor.tsx
while there were no changes. Happened in an eagerly loaded screen after making changes to two fields in a row very fast (pressing tab) and then creating a new row with insert. HandleBlur was called twice. The second call set a dirty value again after it had been handled by an UpdateObject call. The dirty value was never cleared because of logic in clearRecordDirtyValues method in DataTable. The dirty value then caused an UpdateObject to be called after every click.
=> FIX: UpdateObject was running after clicking on any row 2023 1

frontend-html/src/gui/Workbench/ScreenArea/TableView/TableViewEditor.tsx
while there were no changes. Happened in an eagerly loaded screen after making changes to two fields in a row very fast (pressing tab) and then creating a new row with insert. HandleBlur was called twice. The second call set a dirty value again after it had been handled by an UpdateObject call. The dirty value was never cleared because of logic in clearRecordDirtyValues method in DataTable. The dirty value then caused an UpdateObject to be called after every click.
=> FIX: UpdateObject was running after clicking on any row

backend/Origam.Server/Views/Account/LoggedOut.cshtml
Application name removed from log out message. It was always `origamWebClient` for external web applications.
=> FEATURE: Application name removed form log out message

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateEditorModel.ts, frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/cells/dataCellRenderer.ts, frontend-html/src/model/entities/OpenedScreen.ts, frontend-html/src/model/entities/OrigamApiHelpers.ts, frontend-html/src/model/entities/RowState.ts, frontend-html/src/model/entities/WebScreen.ts, frontend-html/src/model/entities/WorkbenchLifecycle/WorkbenchLifecycle.ts, frontend-html/src/model/entities/types/IOpenedScreen.ts, frontend-html/src/model/entities/types/IWorkbenchLifecycle.ts, frontend-html/src/plugins/tools/Localizer.ts, frontend-html/src/xmlInterpreters/getMomentFormat.ts
Some imports were still pointing to recently removed packages
=> FIX: Frontend imports were pointing to removed packages

frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/GroupItem.ts, frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/tableRows.ts, frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/types.ts, frontend-html/src/model/entities/ClientSideGrouper.ts, frontend-html/src/model/entities/ServerSideGrouper.ts, frontend-html/src/modules/Lookup/LookupResolver.ts
<empty> was displayed instead of the grouped column name.
=> FIX: Groups below the first grouping level were missing labels

frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/GroupItem.ts, frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/tableRows.ts, frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/types.ts, frontend-html/src/model/entities/ClientSideGrouper.ts, frontend-html/src/model/entities/ServerSideGrouper.ts, frontend-html/src/modules/Lookup/LookupResolver.ts
<empty> was displayed instead of the grouped column name.
=> FIX: Groups below the first grouping level were missing labels 2024.1

frontend-html/src/gui/Components/ScreenElements/Editors/DateCompleter.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateEditorModel.ts, frontend-html/src/plugins/tools/PluginRegistration.ts, frontend-html/src/tests/DateTimeCompleter.test.ts
if the editor format was set to "time"
=> FIX: Time editor value could not be changed 2024.1

backend/Origam.Server/Controller/BlobController.cs
FIX #3319: https://community.origam.com/t/cannot-open-attachment-via-lookup-from-sd-data-structure-because-it-does-not-contain-blob-column/3319
* Fix to open file even when any BLOB field is not available inside the data structure.
=> FIX: Download file doesn't work if blob member is not specified

backend/Origam.Server/Pages/StandardHttpResponseWrapper.cs
=> FIX: Zip files delivered via FileDownloadPage are invalid

backend/Origam.Server/Pages/StandardHttpResponseWrapper.cs
=> FIX: Zip files delivered via FileDownloadPage are invalid 2023.1

backend/Origam.Server/Pages/StandardHttpResponseWrapper.cs
=> FIX: Zip files delivered via FileDownloadPage are invalid 2023.2

backend/Origam.Server/Pages/StandardHttpResponseWrapper.cs
=> FIX: Zip files delivered via FileDownloadPage are invalid 2024.1

backend/Origam.Server/Pages/StandardHttpResponseWrapper.cs
=> FIX: Zip files delivered via FileDownloadPage are invalid master

frontend-html/public/locale/localization_cs-CZ.json, frontend-html/public/locale/localization_de-CH.json, frontend-html/public/locale/localization_de-DE.json, frontend-html/public/locale/localization_en-US.json, frontend-html/public/locale/localization_fr-CH.json, frontend-html/src/gui/Components/Dropdown/Dropdown.module.scss, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx, model-tests/model/Widgets/Menu/Menu.origam
Changed the default cursor icon from 'pointer' to 'text' when hovering over selected text in a dropdown. When hovering over the text, a tooltip about holding the Ctrl key and clicking the text will show up (in case the text is a link). While holding the key, the cursor icon will switch to 'pointer'. If the text is not a link, then the tooltip will stay hidden. Also, the tooltip message is being translated based on the currently used language.
=> UX - Standardize cursor behavior when hovering over editors

frontend-html/src/gui/Workbench/ScreenArea/FormView/BackupFocusPlaceHolder.module.scss, frontend-html/src/gui/Workbench/ScreenArea/FormView/BackupFocusPlaceHolder.tsx, frontend-html/src/gui/Workbench/ScreenArea/FormView/FormBuilder.tsx, frontend-html/src/model/entities/FormFocusManager.ts
=> FIX: Default action was not executed after pressing enter on empty modal window 2024.2

model-tests/model/AutomaticTests/DeploymentVersion/AutomaticTests/1.0.0.origam___commandText___34639502-577a-4251-9c3c-6a59d3bbeec9.txt, model-tests/model/Widgets/Control/AllDataTypes_Configuration.origam, model-tests/model/Widgets/DataStructure/Widgets/AllDataTypes_Configuration.origam, model-tests/model/Widgets/DeploymentVersion/Widgets/1.5.4.origam, model-tests/model/Widgets/FormControlSet/Widgets/AllDataTypes_Configuration.origam, model-tests/model/Widgets/Menu/Menu.origam, model-tests/model/Widgets/PanelControlSet/Widgets/AllDataTypes_Configuration.origam
See: https://community.origam.com/t/screen-with-defaultconfiguration-adding-new-field-that-should-be-invisible-columnwidth-100-is-visible-in-client/3394/1
=> Screen with configuration new field should be invisible

frontend-html/src/plugins/components/AbstractScreenPlugin.tsx
because of occasional build failures. Probably a VITE issues.
=> FIX: Plugin build error 2024.3

frontend-html/src/plugins/components/AbstractScreenPlugin.tsx
because of occasional build failures. Probably a VITE issues.
=> FIX: Plugin build error 

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx
after selecting a value, clicking outside or pressing esc
=> FIX: Combobox highlighting was not removed after user input had changed

frontend-html/src/model/actions-ui/DataView/TableView/onTableKeyDown.ts, frontend-html/src/model/actions-ui/DataView/onFirstRowClick.ts, frontend-html/src/model/actions-ui/DataView/onLastRowClick.ts, frontend-html/src/model/actions-ui/DataView/onNextRowClick.ts, frontend-html/src/model/actions-ui/DataView/onPrevRowClick.ts
Fixed Record Information not being updated when switching between rows. It should now work both using arrow icons in the data view header as well as the keyboard up and down arrows.
=> FIX: Show Record Information not updated with arrows

frontend-html/src/modules/DataView/DataViewData.ts
…resulted in record not saved error
Happened on MenuItems with the property RequestSaveAfterUpdate set to true.
=> FIX: Modifying a row on a lazy loaded screen and pressing enter sometimes resulted in record not saved error 2024.4

frontend-html/src/modules/DataView/DataViewData.ts
…resulted in record not saved error
Happened on MenuItems with the property RequestSaveAfterUpdate set to true.
=> FIX: Modifying a row on a lazy loaded screen and pressing enter sometimes resulted in record not saved error

frontend-html/src/gui/Components/ScreenElements/Table/Scroller.tsx, frontend-html/src/gui/Components/ScreenElements/Table/Table.tsx, frontend-html/src/gui/Components/ScreenElements/Table/types.ts, frontend-html/src/gui/Workbench/ScreenArea/TableView/TableView.tsx, frontend-html/src/model/entities/TablePanelView/TablePanelView.tsx
Happened on lazy loaded MenuItems with the property RequestSaveAfterUpdate set to true.
=> FIX: Focus was sometimes not set to the active editor after changing a value and pressing enter twice

frontend-html/src/model/actions-ui/DataView/TableView/onFieldKeyDown.ts, frontend-html/src/model/actions-ui/DataView/TableView/onTableKeyDown.ts, frontend-html/src/model/actions/DataView/TableView/selectPrevColumn.ts
Fixed moving focus to a previous cell after pressing Shift+Tab while editing a value.
=> FIX: Shift+Tab doesn't move focus to previous cell

backend/Origam.OrigamEngine/ModelXmlBuilders/FormXmlBuilder.cs
Fixed selection checkboxes column showing up when no action has MultipleCheckboxes mode and no selection member is set.
=> FIX: Selection checkboxes shown when command doesn't require it

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateTimeEditor.tsx
Fixed date field dropdown not closing after pressing Tab/Shift+Tab while editing it.
=> FIX: Date field dropdown doesn't close after pressing Tab

frontend-html/src/gui/Components/Dropdown/Dropdown.module.scss, frontend-html/src/gui/Components/EditorsCommon.module.scss, frontend-html/src/gui/Components/ScreenElements/Editors/BoolEditor.module.scss, frontend-html/src/gui/Components/ScreenElements/Editors/BoolEditor.tsx
Removed the cursor stop icon when hovering over a read-only editor. The stop icon remains only in a read-only checkbox editor.
=> UX: Remove stop cursor when hovering over readonly editor

frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorBehavior.tsx
clicking on dropdown item when editing a combobox value and pressing tab fast after that
=> FIX: Focus lost after click and tab

frontend-html/src/gui/Components/ScreenElements/Table/Table.tsx
If the table was in a popup window. The editor was rendered 15px below its intended position
=> FIX: Editor in table was misaligned 2024.6

frontend-html/src/gui/Components/ScreenElements/Table/Table.tsx
If the table was in a popup window. The editor was rendered 15px below its intended position
=> FIX: Editor in table was misaligned

frontend-html/src/gui/Components/ScreenElements/Table/Table.tsx
If the table was in a popup window. The editor was rendered 15px below its intended position
=> FIX: Editor in table was misaligned 2024.8

.github/workflows/integration-tests.yml, .github/workflows/nunit-tests.yml
because of deprecated actions being used
=> DEV: Tests failing were 2024.8

.github/workflows/integration-tests.yml, .github/workflows/nunit-tests.yml
because of deprecated actions being used
=> DEV: Tests failing were 2024.7

.github/workflows/integration-tests.yml, .github/workflows/nunit-tests.yml
because of deprecated actions being used
=> DEV: Tests failing were 2024.6

backend/Origam.Workflow/WorkQueue/WorkQueueIncrementalFileLoader.cs
Fixes [https://github.com/origam/origam/security/code-scanning/22](https://github.com/origam/origam/security/code-scanning/22)
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert #22: Arbitrary file access during archive extraction ("Zip Slip")

backend/Origam.Server/Controller/AbstractController.cs
was included in the http response when a validation exception occured
=> FIX: Stack trace was shown in production environment

docker/_appsettings.template
Corrected typo in Czech language name in _appsettings.template for Docker
=> FIX: Typo in language name in _appsettings.template for Docker

docker/_appsettings.template
because it was not possible to remove them when the docker container was deployed
=> DEV: Removed redundant languages from appsettings docker template

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateTimeEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/NumberEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/TagInputEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/TextEditor.tsx, frontend-html/src/modules/DataView/DataViewData.ts, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx
It was possible to drag and drop values between inputs on form leading to confusing/wrong results
(cherry picked from commit b40cc6e23db19efeb5a19cf71beb971a98a0bb85)
=> UX: Preventing drag and drop values between inputs 2024.9

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateTimeEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/NumberEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/TagInputEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/TextEditor.tsx, frontend-html/src/modules/DataView/DataViewData.ts, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx
It was possible to drag and drop values between inputs on form leading to confusing/wrong results
(cherry picked from commit b40cc6e23db19efeb5a19cf71beb971a98a0bb85)
=> UX: Preventing drag and drop values between inputs 2024.10

frontend-html/src/gui/Components/ScreenElements/Editors/DateTimeEditor/DateTimeEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/NumberEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/TagInputEditor.tsx, frontend-html/src/gui/Components/ScreenElements/Editors/TextEditor.tsx, frontend-html/src/modules/DataView/DataViewData.ts, frontend-html/src/modules/Editors/DropdownEditor/DropdownEditorInput.tsx
It was possible to drag and drop values between inputs on form leading to confusing/wrong results
(cherry picked from commit b40cc6e23db19efeb5a19cf71beb971a98a0bb85)
=> UX: Preventing drag and drop values between inputs 2024.11

.github/workflows/integration-tests.yml
Host machine got updated and it suddenly started to report package vulnerabilities. Some of the vulnerabilities are not in direct references and they're difficult to solved. So vulnerability warnings are not going be treated as errors.
https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-restore-audit
=> BUILD: Vulnerability warnings are not treated as errors.

backend/Origam.Workflow/WorkQueue/WorkQueueService.cs
https://community.origam.com/t/error-while-calling-getnotificationcontacts-from-workqueueservice-contextstore-not-found/3897
=> FIX: Notification context store wasn't aligned with the model

backend/Origam.Workflow/WorkQueue/WorkQueueService.cs
One of the input contextstores of GetNotificationContacts workflow was called from WorkQueueService with a slightly different name than in the model => rename of origamNotificationChannelTypeId -> OrigamNotificationChannelTypeId (align with the model).
https://community.origam.com/t/error-while-calling-getnotificationcontacts-from-workqueueservice-contextstore-not-found/3897
=> FIX: Notification context store wasn't aligned with the model (#3001)

backend/Origam.Security.Common/AccountMailSender.cs, backend/Origam.Server/Authorization/IMailService.cs, backend/Origam.Server/Authorization/MailService.cs, backend/Origam.Server/IdentityServerGui/Account/AccountController.cs, backend/Origam.Server/IdentityServerGui/Account/ForgotPasswordViewModel.cs, backend/Origam.Server/IdentityServerGui/Account/ResetPasswordConfirmationViewModel.cs, backend/Origam.Server/IdentityServerGui/Account/ResetPasswordViewModel.cs, backend/Origam.Server/Views/Account/ForgotPassword.cshtml, backend/Origam.Server/Views/Account/Login.cshtml, backend/Origam.Server/Views/Account/ResetPassword.cshtml, backend/Origam.Server/Views/Account/ResetPasswordConfirmation.cshtml
* Changing language doesn't mean the user will login into the Origam application instead of the external one.
* Reset password now keeps returnUrl through the whole process to be able to login into the application from where the process was initiated.
=> FEATURE: Improved support for external application using Origam authentication

backend/Origam.Workflow/WorkQueue/WorkQueueWorkflowLoader.cs
Workflow loader accepted only results of `XmlContainer` type, preventing `DataDocumentCore`. Now the result is expected to be of `IXmlContainer` type, thus accepting both `XmlContainer` and `DataDocumentCore`.
=> FIX: Work queue workflow loader DataDocumentCore result not supported

model-root/model/Security/.origamPackage, model-root/model/Security/DeploymentVersion/Security/5.4.4.origam, model-root/model/Security/DeploymentVersion/Security/5.4.4.origam___commandText___bbf3b60d-e7ad-4630-a59f-d1f297c1ff4a.txt, model-root/model/Security/DeploymentVersion/Security/5.4.4.origam___commandText___e4a3c394-5c9b-467c-b13e-4a226c035843.txt, model-tests/model/Security/.origamPackage, model-tests/model/Security/DeploymentVersion/Security/5.4.1.origam, model-tests/model/Security/DeploymentVersion/Security/5.4.4.origam, model-tests/model/Security/DeploymentVersion/Security/5.4.4.origam___commandText___bbf3b60d-e7ad-4630-a59f-d1f297c1ff4a.txt, model-tests/model/Security/DeploymentVersion/Security/5.4.4.origam___commandText___e4a3c394-5c9b-467c-b13e-4a226c035843.txt
Expiration date is stored in UTC, clean up store procedure updated so it uses UTC now.
=> FIX: Server cleans up valid tokens during bootup

architect-html/src/components/editors/xsltEditor/XsltEditor.tsx, backend/Origam.Architect.Server/Services/PropertyEditorService.cs
To update the XSLT editor to dynamically determine the correct property name (‘TextStore’ or ‘Xsl’) based on available properties, ensuring proper data binding and filtering.
=> FIX: XSLT editor property handling + missing tab label
